//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAffairs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Users = new HashSet<User>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> JopId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string NumberId { get; set; }
        public string Image { get; set; }
        public string BirthDate { get; set; }
        public string Qualification { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> MaritalStateId { get; set; }
        public Nullable<System.Guid> RegistrationTypeId { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string JoiningDate { get; set; }
        public Nullable<double> WorkDayCost { get; set; }
        public bool ContractOrNo { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
    
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
