//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAffairs.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentAffairsEntities : DbContext
    {
        public StudentAffairsEntities()
            : base("name=StudentAffairsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CityDepartment> CityDepartments { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EndYearResult> EndYearResults { get; set; }
        public virtual DbSet<ExemptionReason> ExemptionReasons { get; set; }
        public virtual DbSet<ExitPermission> ExitPermissions { get; set; }
        public virtual DbSet<ExpenseType> ExpenseTypes { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<RegistrationStatu> RegistrationStatus { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<SchoolInfo> SchoolInfoes { get; set; }
        public virtual DbSet<ScienceDivision> ScienceDivisions { get; set; }
        public virtual DbSet<SecondLanguage> SecondLanguages { get; set; }
        public virtual DbSet<SecondRoundResult> SecondRoundResults { get; set; }
        public virtual DbSet<SocialStatu> SocialStatus { get; set; }
        public virtual DbSet<StudentAttachment> StudentAttachments { get; set; }
        public virtual DbSet<StudentReceipt> StudentReceipts { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentsAttendance> StudentsAttendances { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
