//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAffairs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsAttendance
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> StudentId { get; set; }
        public Nullable<System.Guid> LevelId { get; set; }
        public Nullable<System.Guid> ClassId { get; set; }
        public Nullable<System.DateTime> AttendDate { get; set; }
        public Nullable<bool> AttendOrNo { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Level Level { get; set; }
        public virtual Student Student { get; set; }
    }
}
