//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAffairs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.ExitPermissions = new HashSet<ExitPermission>();
            this.StudentAttachments = new HashSet<StudentAttachment>();
            this.StudentReceipts = new HashSet<StudentReceipt>();
            this.StudentsAttendances = new HashSet<StudentsAttendance>();
        }
    
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string SerialNumber { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Phone { get; set; }
        public Nullable<System.Guid> LevelId { get; set; }
        public Nullable<System.Guid> ClassId { get; set; }
        public string SeatNumber { get; set; }
        public Nullable<System.Guid> ReligionId { get; set; }
        public Nullable<System.Guid> NationalityId { get; set; }
        public Nullable<System.Guid> ExpenseTypeId { get; set; }
        public Nullable<System.Guid> ExemptionReasonId { get; set; }
        public Nullable<System.Guid> EndYearResultId { get; set; }
        public Nullable<System.Guid> SecondRoundResultId { get; set; }
        public string HealthCondition { get; set; }
        public string FirstSemesterResult { get; set; }
        public Nullable<int> EducationalIntegration { get; set; }
        public Nullable<int> TransferredToTheSchool { get; set; }
        public string Address { get; set; }
        public string NumberId { get; set; }
        public string BirthDate { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<System.Guid> RegistrationStateId { get; set; }
        public string RegistrationNum { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string ParentName { get; set; }
        public string ParentAddress { get; set; }
        public string ParentJob { get; set; }
        public string ParentPhone { get; set; }
        public string ParentWhatsApp { get; set; }
        public string MotherName { get; set; }
        public string MotherPhone { get; set; }
        public Nullable<System.Guid> SocialStateId { get; set; }
        public string TabletSerialNumber { get; set; }
        public Nullable<System.Guid> ScienceDivisionId { get; set; }
        public string IM { get; set; }
        public Nullable<System.Guid> SecondLanguageId { get; set; }
        public Nullable<System.DateTime> DateOfReceipt { get; set; }
        public string InsurancePolicyNumber { get; set; }
        public Nullable<System.DateTime> InsurancePolicyDate { get; set; }
        public string ProtectionCommittee { get; set; }
        public string Duration { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Problem { get; set; }
        public string ActionTaken { get; set; }
        public string Talents { get; set; }
        public string Competitions { get; set; }
        public Nullable<int> StudentTypeId { get; set; }
        public Nullable<System.Guid> SchoolId { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
    
        public virtual City City { get; set; }
        public virtual Class Class { get; set; }
        public virtual EndYearResult EndYearResult { get; set; }
        public virtual ExemptionReason ExemptionReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExitPermission> ExitPermissions { get; set; }
        public virtual ExpenseType ExpenseType { get; set; }
        public virtual Level Level { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual RegistrationStatu RegistrationStatu { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual SchoolInfo SchoolInfo { get; set; }
        public virtual ScienceDivision ScienceDivision { get; set; }
        public virtual SecondLanguage SecondLanguage { get; set; }
        public virtual SecondRoundResult SecondRoundResult { get; set; }
        public virtual SocialStatu SocialStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAttachment> StudentAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentReceipt> StudentReceipts { get; set; }
        public virtual Student Students1 { get; set; }
        public virtual Student Student1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsAttendance> StudentsAttendances { get; set; }
    }
}
